---
version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./config:/config
      - ./tv:/tv
      - ./movies:/movies
    restart: always