apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: plex-volume-config
  name: plex-volume-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
