apiVersion: v1
kind: Service
metadata:
  labels:
    name: plex
  name: plex
spec:
  ports:
    - name: "32400"
      port: 32400
      targetPort: 32400
  selector:
    name: plex
status:
  loadBalancer: {}
